SELECT * FROM sql_practice.dbo.DEPT

SELECT * into TABLE_A FROM DEPT where 1 =2

SELECT * from TABLE_A

insert into TABLE_A Select * from DEPT

SELECT * from TABLE_A
SELECT * FROM DEPT

SELECT DEPT.DEPTNO, TABLE_A.DEPTNO
FROM DEPT CROSS JOIN TABLE_A